<?php

return [
    'modules' => [
        'dashboard' => 'Tableau de bord & Profil',
        'users' => 'Utilisateurs & Accès',
        'students' => 'Élèves',
        'registrations' => 'Inscriptions',
        'parents' => 'Parents & Tuteurs',
        'family' => 'Espace famille (portail parent)',
        'classrooms' => 'Classes & Niveaux',
        'teachers' => 'Professeurs',
        'programmes' => 'Programmes annuels & Cahier de textes',
        'pedagogy' => 'Configuration pédagogique',
        'payments' => 'Paiements & Finances',
        'invoices' => 'Factures',
        'fees' => 'Grille tarifaire',
        'reports' => 'Rapports financiers',
        'attendances' => 'Présences',
        'notifications' => 'Notifications & Communications',
        'school-years' => 'Années scolaires',
        'admin' => 'Super-Admin',
    ],

    'labels' => [
        'voir-dashboard' => 'Consulter le tableau de bord',
        'voir-profil' => 'Voir son profil',
        'modifier-profil' => 'Modifier son profil',
        'supprimer-compte' => 'Supprimer son compte',

        'voir-utilisateurs' => 'Voir les utilisateurs',
        'creer-utilisateur' => 'Créer un utilisateur',
        'modifier-utilisateur' => 'Modifier un utilisateur',
        'supprimer-utilisateur' => 'Supprimer un utilisateur',
        'activer-desactiver-utilisateur' => 'Activer / désactiver un utilisateur',
        'reinitialiser-mot-de-passe-utilisateur' => 'Réinitialiser un mot de passe',

        'voir-eleves' => 'Voir les élèves',
        'voir-detail-eleve' => 'Voir le détail d’un élève',
        'transferer-eleve' => 'Transférer un élève',
        'modifier-statut-eleve' => 'Modifier le statut d’un élève',
        'upload-photo-eleve' => 'Ajouter une photo d’élève',
        'gerer-documents-eleve' => 'Gérer les documents d’un élève',

        'voir-inscriptions' => 'Voir les inscriptions',
        'creer-inscription' => 'Créer une inscription',
        'promouvoir-eleves' => 'Utiliser l\'assistant de promotion des élèves',

        'voir-parents' => 'Voir les parents',
        'creer-parent' => 'Créer un parent',
        'modifier-parent' => 'Modifier un parent',
        'voir-detail-parent' => 'Voir le détail d’un parent',
        'archiver-parent' => 'Archiver un parent',
        'restaurer-parent' => 'Restaurer un parent',
        'supprimer-parent' => 'Supprimer un parent',
        'associer-eleve-parent' => 'Associer un élève à un parent',
        'dissocier-eleve-parent' => 'Dissocier un élève d’un parent',
        'reinitialiser-mot-de-passe-parent' => 'Réinitialiser le mot de passe d’un parent',

        'voir-classes' => 'Voir les classes',
        'creer-classe' => 'Créer une classe',
        'modifier-classe' => 'Modifier une classe',
        'supprimer-classe' => 'Supprimer une classe',
        'affecter-professeur' => 'Affecter un professeur',
        'gerer-enseignants-classe' => 'Gérer les enseignants d’une classe',

        'voir-professeurs' => 'Voir les professeurs',
        'creer-professeur' => 'Créer un professeur',
        'modifier-professeur' => 'Modifier un professeur',
        'supprimer-professeur' => 'Supprimer un professeur',
        'voir-rib-professeur' => 'Voir les coordonnées bancaires',

        'voir-annees-scolaires' => 'Voir les années scolaires',
        'creer-annee-scolaire' => 'Créer une année scolaire',
        'modifier-annee-scolaire' => 'Modifier une année scolaire',
        'supprimer-annee-scolaire' => 'Supprimer une année scolaire',
        'activer-annee-scolaire' => 'Activer une année scolaire',
        'cloturer-annee-scolaire' => 'Démarrer/annuler la clôture d\'une année scolaire',
        'deverrouiller-annee-scolaire' => 'Rouvrir exceptionnellement une année clôturée (Super Admin uniquement)',

        'voir-paiements' => 'Voir les paiements',
        'enregistrer-paiement' => 'Enregistrer un paiement',
        'valider-paiement-partiel' => 'Valider un paiement partiel',
        'annuler-paiement' => 'Annuler un paiement',
        'modifier-paiement' => 'Modifier un paiement',
        'supprimer-paiement' => 'Supprimer un paiement',
        'voir-comptabilite' => 'Voir la comptabilité',
        'voir-finances' => 'Voir les finances',
        'voir-recouvrement' => 'Voir le recouvrement',

        'voir-factures' => 'Voir les factures',
        'creer-facture' => 'Créer une facture',
        'modifier-facture' => 'Modifier une facture',
        'supprimer-facture' => 'Supprimer une facture',

        'voir-types-frais' => 'Voir les types de frais',
        'creer-type-frais' => 'Créer un type de frais',
        'modifier-type-frais' => 'Modifier un type de frais',
        'supprimer-type-frais' => 'Supprimer un type de frais',

        'voir-frais-classe' => 'Voir les frais par classe',
        'creer-frais-classe' => 'Créer des frais par classe',
        'modifier-frais-classe' => 'Modifier des frais par classe',
        'supprimer-frais-classe' => 'Supprimer des frais par classe',
        'gerer-derogations-tarifaires' => 'Gérer les dérogations tarifaires exceptionnelles',

        'voir-rapports-financiers' => 'Voir les rapports financiers',
        'voir-rapports-avances' => 'Voir les rapports avancés',
        'exporter-rapports-excel' => 'Exporter les rapports Excel',
        'voir-alertes-impayes' => 'Voir les alertes impayés',
        'voir-tresorerie' => 'Voir la trésorerie',

        'voir-sa-classe' => 'Voir ses classes',
        'saisir-notes' => 'Saisir les notes',
        'valider-notes' => 'Valider les notes (verrouillage)',
        'rouvrir-notes-validees' => 'Rouvrir des notes validées',
        'marquer-absences' => 'Marquer les absences',
        'generer-bulletins' => 'Créer et générer les bulletins',

        'voir-ses-enfants' => 'Voir ses enfants',
        'voir-ses-paiements-enfants' => 'Voir les paiements de ses enfants',
        'voir-ses-notes-enfants' => 'Voir les notes de ses enfants',
        'voir-ses-bulletins-enfants' => 'Voir les bulletins de ses enfants',
        'voir-ses-discipline-enfants' => 'Voir la discipline de ses enfants',
        'voir-emploi-du-temps' => 'Voir l’emploi du temps de ses enfants',
        'voir-messagerie' => 'Accéder à la messagerie',
        'voir-calendrier-scolaire' => 'Voir le calendrier scolaire',

        'voir-logs-connexion' => 'Voir les logs de connexion',
        'voir-detail-log-connexion' => 'Voir le détail d’un log',

        'voir-notifications' => 'Voir les notifications',
        'creer-notification' => 'Créer une notification',
        'publier-notification' => 'Publier une notification',
        'programmer-notification' => 'Programmer une notification',
        'modifier-notification' => 'Modifier une notification',
        'archiver-notification' => 'Archiver une notification',
        'voir-historique-notifications' => 'Voir l’historique des notifications',
        'voir-statistiques-lecture' => 'Voir les statistiques de lecture',

        'voir-programmes' => 'Voir les programmes annuels',
        'creer-programme' => 'Créer un programme annuel',
        'modifier-programme' => 'Modifier un programme annuel',
        'soumettre-programme' => 'Soumettre un programme',
        'supprimer-programme' => 'Supprimer un programme',
        'valider-programme-surveillant' => 'Valider un programme (ancienne étape surveillant, non utilisée)',
        'valider-programme-directeur' => 'Valider un programme (administrateur)',
        'rejeter-programme' => 'Rejeter un programme',
        'voir-cahier-textes' => 'Voir le cahier de textes',
        'saisir-cahier-textes' => 'Saisir le cahier de textes',
        'modifier-cahier-textes' => 'Modifier le cahier de textes',
        'voir-tableau-bord-cahier-textes' => 'Voir le tableau de bord du cahier',
        'voir-historique-cahier-textes' => 'Voir l’historique du cahier',

        'tout-faire' => 'Tous les droits (Super-Admin)',
    ],

    'modules_map' => [
        'dashboard' => ['voir-dashboard', 'voir-profil', 'modifier-profil', 'supprimer-compte'],
        'users' => ['voir-utilisateurs', 'creer-utilisateur', 'modifier-utilisateur', 'supprimer-utilisateur', 'activer-desactiver-utilisateur', 'reinitialiser-mot-de-passe-utilisateur'],
        'students' => ['voir-eleves', 'voir-detail-eleve', 'transferer-eleve', 'modifier-statut-eleve', 'upload-photo-eleve', 'gerer-documents-eleve'],
        'registrations' => ['voir-inscriptions', 'creer-inscription', 'promouvoir-eleves'],
        'parents' => ['voir-parents', 'creer-parent', 'modifier-parent', 'voir-detail-parent', 'archiver-parent', 'restaurer-parent', 'supprimer-parent', 'associer-eleve-parent', 'dissocier-eleve-parent', 'reinitialiser-mot-de-passe-parent'],
        'family' => ['voir-ses-enfants', 'voir-ses-paiements-enfants', 'voir-ses-notes-enfants', 'voir-ses-bulletins-enfants', 'voir-ses-discipline-enfants', 'voir-emploi-du-temps', 'voir-messagerie', 'voir-calendrier-scolaire'],
        'classrooms' => ['voir-classes', 'creer-classe', 'modifier-classe', 'supprimer-classe', 'affecter-professeur', 'gerer-enseignants-classe'],
        'teachers' => ['voir-professeurs', 'creer-professeur', 'modifier-professeur', 'supprimer-professeur', 'voir-rib-professeur'],
        'school-years' => ['voir-annees-scolaires', 'creer-annee-scolaire', 'modifier-annee-scolaire', 'supprimer-annee-scolaire', 'activer-annee-scolaire', 'cloturer-annee-scolaire', 'deverrouiller-annee-scolaire'],
        'payments' => ['voir-paiements', 'enregistrer-paiement', 'valider-paiement-partiel', 'annuler-paiement', 'modifier-paiement', 'supprimer-paiement', 'voir-comptabilite', 'voir-finances', 'voir-recouvrement'],
        'invoices' => ['voir-factures', 'creer-facture', 'modifier-facture', 'supprimer-facture'],
        'fees' => ['voir-types-frais', 'creer-type-frais', 'modifier-type-frais', 'supprimer-type-frais', 'voir-frais-classe', 'creer-frais-classe', 'modifier-frais-classe', 'supprimer-frais-classe', 'gerer-derogations-tarifaires'],
        'reports' => ['voir-rapports-financiers', 'voir-rapports-avances', 'exporter-rapports-excel', 'voir-alertes-impayes', 'voir-tresorerie'],
        'attendances' => ['marquer-absences'],
        'grades' => ['voir-sa-classe', 'saisir-notes', 'valider-notes', 'rouvrir-notes-validees', 'generer-bulletins'],
        'notifications' => ['voir-notifications', 'creer-notification', 'publier-notification', 'programmer-notification', 'modifier-notification', 'archiver-notification', 'voir-historique-notifications', 'voir-statistiques-lecture'],
        'programmes' => ['voir-programmes', 'creer-programme', 'modifier-programme', 'soumettre-programme', 'supprimer-programme', 'valider-programme-surveillant', 'valider-programme-directeur', 'rejeter-programme', 'voir-cahier-textes', 'saisir-cahier-textes', 'modifier-cahier-textes', 'voir-tableau-bord-cahier-textes', 'voir-historique-cahier-textes'],
        'admin' => ['tout-faire'],
    ],

    'sensitive_roles' => [
        'super-admin',
        'manager-comptable',
        'comptable',
        'admin',
    ],

    'sensitive_permissions' => [
        'tout-faire',
        'voir-finances',
        'voir-comptabilite',
        'voir-paiements',
        'valider-paiement-partiel',
        'supprimer-paiement',
        'modifier-paiement',
        'voir-rapports-financiers',
        'voir-tresorerie',
        'voir-utilisateurs',
        'creer-utilisateur',
        'modifier-utilisateur',
        'supprimer-utilisateur',
        'activer-desactiver-utilisateur',
        'reinitialiser-mot-de-passe-utilisateur',
        'valider-programme-surveillant',
        'valider-programme-directeur',
        'rouvrir-notes-validees',
    ],
];
