<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-800 dark:text-gray-100">Configuration pédagogique</h2></x-slot>
    <div class="py-8" x-data="{ tab: new URLSearchParams(location.search).get('tab') || 'overview' }">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <form method="GET" class="flex items-end gap-3 rounded-lg bg-white p-4 shadow-sm dark:bg-slate-800"><div><label class="block text-sm font-medium text-gray-700 dark:text-gray-300">Année scolaire</label><select name="school_year_id" class="mt-1 rounded-md border-gray-300 dark:border-slate-600 dark:bg-slate-900 dark:text-white">@foreach($schoolYears as $year)<option value="{{ $year->id }}" @selected($schoolYear?->id === $year->id)>{{ $year->year_string }}</option>@endforeach</select></div><button class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Afficher</button></form>
            @if(! $schoolYear)<div class="rounded-lg bg-amber-50 p-6 text-amber-800">Créez puis activez une année scolaire avant de configurer la pédagogie.</div>@else
            <div class="overflow-x-auto rounded-lg bg-white shadow-sm dark:bg-slate-800"><nav class="flex min-w-max border-b border-gray-200 dark:border-slate-700">@foreach(['overview' => 'Vue générale', 'assignments' => 'Affectations', 'subjects' => 'Matières & coefficients', 'evaluations' => 'Évaluations', 'periods' => 'Périodes', 'grades' => 'Notes & verrouillage'] as $key => $label)<button @click="tab = '{{ $key }}'" :class="tab === '{{ $key }}' ? 'border-indigo-600 text-indigo-600 dark:text-indigo-400' : 'border-transparent text-gray-500'" class="border-b-2 px-4 py-3 text-sm font-medium">{{ $label }}</button>@endforeach</nav></div>

            <section x-show="tab === 'overview'" class="space-y-6"><div class="grid grid-cols-1 gap-4 md:grid-cols-4"><div class="rounded-lg bg-indigo-600 p-5 text-white"><p class="text-sm">Année active</p><p class="mt-1 text-2xl font-bold">{{ $schoolYear->year_string }}</p></div><div class="rounded-lg bg-white p-5 shadow-sm dark:bg-slate-800"><p class="text-sm text-gray-500">Classes</p><p class="text-2xl font-bold dark:text-white">{{ $classrooms->count() }}</p></div><div class="rounded-lg bg-white p-5 shadow-sm dark:bg-slate-800"><p class="text-sm text-gray-500">Matières</p><p class="text-2xl font-bold dark:text-white">{{ $configuredSubjects->count() }}</p></div><div class="rounded-lg bg-white p-5 shadow-sm dark:bg-slate-800"><p class="text-sm text-gray-500">Affectations</p><p class="text-2xl font-bold dark:text-white">{{ $assignments->count() }}</p></div></div><div class="rounded-lg bg-white p-6 shadow-sm dark:bg-slate-800"><h3 class="font-semibold text-gray-900 dark:text-white">Configuration à compléter</h3><div class="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2">@foreach($issues as $issue)<button @click="tab = '{{ $issue['tab'] }}'" class="flex items-center justify-between rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-left text-sm text-amber-900"><span>{{ $issue['label'] }}</span><strong>{{ $issue['count'] }}</strong></button>@endforeach</div></div></section>

            <section x-show="tab === 'assignments'" class="rounded-lg bg-white p-6 shadow-sm dark:bg-slate-800"><div class="flex items-center justify-between"><div><h3 class="font-semibold text-gray-900 dark:text-white">Affectations pédagogiques</h3><p class="mt-1 text-sm text-gray-500">Professeur, classe, matière et année scolaire.</p></div><a href="{{ route('pedagogical-configuration.assignments', ['school_year_id' => $schoolYear->id]) }}" class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Gérer les affectations</a></div></section>

            <section x-show="tab === 'subjects'" class="rounded-lg bg-white p-6 shadow-sm dark:bg-slate-800"><h3 class="font-semibold text-gray-900 dark:text-white">Coefficients par cycle</h3><form method="POST" action="{{ route('pedagogical-configuration.subjects.store') }}" class="mt-4 grid grid-cols-1 gap-3 md:grid-cols-4">@csrf<input type="hidden" name="school_year_id" value="{{ $schoolYear->id }}"><select name="matiere_id" class="rounded-md border-gray-300">@foreach(\App\Models\Matiere::orderBy('nom')->get() as $matiere)<option value="{{ $matiere->id }}">{{ $matiere->nom }}</option>@endforeach</select><select name="cycle" class="rounded-md border-gray-300"><option value="">Tous les cycles</option><option value="primaire">Primaire</option><option value="college">Collège</option><option value="lycee">Lycée</option></select><input name="coefficient" type="number" min="0.1" step="0.1" value="1" class="rounded-md border-gray-300"><button class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Enregistrer</button></form><div class="mt-5 divide-y dark:divide-slate-700">@forelse($configuredSubjects as $configuration)<div class="flex justify-between py-3 text-sm dark:text-gray-200"><span>{{ $configuration->matiere?->nom ?? 'Matière' }} — {{ $configuration->cycle ?: 'Tous cycles' }}</span><strong>Coef. {{ $configuration->coefficient }}</strong></div>@empty<p class="py-4 text-sm text-gray-500">Aucun coefficient spécifique configuré.</p>@endforelse</div></section>

            <section x-show="tab === 'evaluations'" class="rounded-lg bg-white p-6 shadow-sm dark:bg-slate-800"><h3 class="font-semibold text-gray-900 dark:text-white">Types d’évaluation</h3><form method="POST" action="{{ route('pedagogical-configuration.evaluation-types.store') }}" class="mt-4 grid grid-cols-1 gap-3 md:grid-cols-4">@csrf<input name="name" placeholder="Ex. Composition" class="rounded-md border-gray-300" required><input name="default_coefficient" type="number" step="0.1" min="0.1" value="1" class="rounded-md border-gray-300" required><select name="default_scale" class="rounded-md border-gray-300"><option>20</option><option>10</option><option>40</option><option>100</option></select><button class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Ajouter</button></form><div class="mt-5 divide-y dark:divide-slate-700">@forelse(\App\Models\EvaluationType::orderBy('position')->get() as $type)<div class="flex justify-between py-3 text-sm dark:text-gray-200"><span>{{ $type->name }}</span><span>Coef. {{ $type->default_coefficient }} · /{{ $type->default_scale }}</span></div>@empty<p class="py-4 text-sm text-gray-500">Aucun type d’évaluation configuré.</p>@endforelse</div></section>

            <section x-show="tab === 'periods'" class="rounded-lg bg-white p-6 shadow-sm dark:bg-slate-800"><h3 class="font-semibold text-gray-900 dark:text-white">Périodes scolaires</h3><form method="POST" action="{{ route('pedagogical-configuration.periods.store') }}" class="mt-4 grid grid-cols-1 gap-3 md:grid-cols-3">@csrf<input type="hidden" name="school_year_id" value="{{ $schoolYear->id }}"><input name="name" placeholder="Trimestre 1" class="rounded-md border-gray-300" required><input name="starts_at" type="date" class="rounded-md border-gray-300" required><input name="ends_at" type="date" class="rounded-md border-gray-300" required><input name="grade_entry_starts_at" type="date" class="rounded-md border-gray-300"><input name="grade_entry_ends_at" type="date" class="rounded-md border-gray-300"><button class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Ajouter la période</button></form><div class="mt-5 divide-y dark:divide-slate-700">@forelse($periods as $period)<div class="flex items-center justify-between py-3 text-sm dark:text-gray-200"><span>{{ $period->name }} · {{ $period->starts_at->format('d/m/Y') }} — {{ $period->ends_at->format('d/m/Y') }}</span><form method="POST" action="{{ route('pedagogical-configuration.periods.toggle', $period) }}">@csrf @method('PATCH')<button class="rounded-md px-3 py-1 {{ $period->grade_entry_open ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-700' }}">{{ $period->grade_entry_open ? 'Saisie ouverte' : 'Saisie fermée' }}</button></form></div>@empty<p class="py-4 text-sm text-gray-500">Aucune période configurée.</p>@endforelse</div></section>

            <section x-show="tab === 'grades'" class="rounded-lg bg-white p-6 shadow-sm dark:bg-slate-800"><h3 class="font-semibold text-gray-900 dark:text-white">Règles de gestion des notes</h3>@php($settings = $schoolYear->gradeSetting) <form method="POST" action="{{ route('pedagogical-configuration.settings.update', $schoolYear) }}" class="mt-4 grid grid-cols-1 gap-4 md:grid-cols-3">@csrf @method('PUT')<select name="organization_mode" class="rounded-md border-gray-300"><option value="trimesters" @selected($settings?->organization_mode === 'trimesters')>Trimestres</option><option value="semesters" @selected($settings?->organization_mode === 'semesters')>Semestres</option></select><select name="default_scale" class="rounded-md border-gray-300">@foreach([10,20,40,100] as $scale)<option value="{{ $scale }}" @selected(($settings?->default_scale ?? 20) === $scale)>Barème /{{ $scale }}</option>@endforeach</select><input type="number" name="minimum_grade" step="0.1" value="{{ $settings?->minimum_grade ?? 0 }}" class="rounded-md border-gray-300">@foreach(['allow_decimals' => 'Autoriser les décimales', 'allow_appreciations' => 'Autoriser les appréciations', 'allow_edit_after_submission' => 'Modification après soumission', 'administrative_validation_required' => 'Validation administrative obligatoire', 'lock_after_validation' => 'Verrouillage après validation'] as $field => $label)<label class="flex items-center gap-2 text-sm dark:text-gray-200"><input type="checkbox" name="{{ $field }}" value="1" @checked($settings?->$field ?? ($field === 'allow_decimals' || $field === 'allow_appreciations'))>{{ $label }}</label>@endforeach<button class="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Enregistrer les règles</button></form></section>
            @endif
        </div>
    </div>
</x-app-layout>
